apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-san-block-svm0-delete
parameters:
  backendType:      "ontap-san"
  sanType:          "nvme"
  storagePools:     "svm0-nvme:.*"    # tie to the 'svm0-file' backend
  provisioningType: "thin"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
provisioner: csi.trident.netapp.io