apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-nas-file-svm0-retain
provisioner: csi.trident.netapp.io
parameters:
  backendType:      "ontap-nas"
  storagePools:     "svm0-rt1-file:.*"
  provisioningType: "thin"
  media:            "ssd"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true