---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-tool
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ontap-nas-file-svm10-delete
  resources:
    requests:
      storage: 1Gi
